# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Highway"
license = "MIT"
licenselink = "https://github.com/wjiec/hugo-highway/blob/master/LICENSE"
description = "Highway is a clean hugo theme"
homepage = "https://github.com/wjiec/hugo-highway"
tags = ["blog", "responsive"]
features = ["blog", "responsive"]
min_version = "0.41.0"

[author]
  name = "Jayson Wang"
  homepage = "https://jayson.wang"
